
// Define an enum for the different case types
export enum CaseType {
  Civil = "Civil",
  Employment = "Employment",
  Commercial = "Commercial",
  Personal_Injury = "Personal Injury",
  Administrative = "Administrative",
  Financial = "Financial",
  Consumer = "Consumer",
  Family_Law = "Family Law",
  Intellectual_Property = "Intellectual Property",
  Real_Estate = "Real Estate",
  Insurance = "Insurance",
  Other = "Other",
}

export interface Case {
    case_title: string;
    case_description: string;
    case_type: CaseType;
    filing_date: string; // Format: YYYY-MM-DD
    causeOfAction: string;
    urgency_level: string; // E.g., 'High', 'Medium', 'Low'
    plaintiffName: string;
    plaintiffContactEmail: string;
    plaintiffContactPhone: string;
    plaintiffAddress: string;
    defendantName: string;
    defendantContactEmail: string;
    defendantContactPhone: string;
    defendantAddress: string;
    evidence_provided: string;
    witness_details: string;
    case_status: "Filed" | "Requested" | "Registered" | "Closed" | "Rejected" | "Accepted";
}

const cases: Case[] = [
    {
        case_title: "Jones vs. Taylor",
        case_description: "Contract dispute over unpaid invoices.",
        case_type: CaseType.Commercial,
        filing_date: "2024-02-20",
        causeOfAction: "Breach of Contract",
        urgency_level: "High",
        plaintiffName: "Michael Jones",
        plaintiffContactEmail: "michael.jones@example.com",
        plaintiffContactPhone: "555-0101",
        plaintiffAddress: "789 Maple Ave, Springfield, IL",
        defendantName: "Laura Taylor",
        defendantContactEmail: "laura.taylor@example.com",
        defendantContactPhone: "555-0102",
        defendantAddress: "321 Oak St, Springfield, IL",
        evidence_provided: "Email correspondence, signed contracts.",
        witness_details: "Sarah Connor.",
        case_status: "Filed",
      },
      {
        case_title: "Garcia vs. Martinez",
        case_description: "Personal injury claim from a car accident.",
        case_type: CaseType.Personal_Injury,
        filing_date: "2024-03-05",
        causeOfAction: "Negligence",
        urgency_level: "High",
        plaintiffName: "Luis Garcia",
        plaintiffContactEmail: "luis.garcia@example.com",
        plaintiffContactPhone: "555-0111",
        plaintiffAddress: "234 Pine St, Springfield, IL",
        defendantName: "Carlos Martinez",
        defendantContactEmail: "carlos.martinez@example.com",
        defendantContactPhone: "555-0112",
        defendantAddress: "567 Birch St, Springfield, IL",
        evidence_provided: "Police report, medical records.",
        witness_details: "Emily White.",
        case_status: "Requested",
      },
      {
        case_title: "Lee vs. Wang",
        case_description: "Dispute regarding a loan repayment.",
        case_type: CaseType.Financial,
        filing_date: "2024-04-12",
        causeOfAction: "Debt Recovery",
        urgency_level: "Medium",
        plaintiffName: "Henry Lee",
        plaintiffContactEmail: "henry.lee@example.com",
        plaintiffContactPhone: "555-0123",
        plaintiffAddress: "890 Cedar St, Springfield, IL",
        defendantName: "Wei Wang",
        defendantContactEmail: "wei.wang@example.com",
        defendantContactPhone: "555-0124",
        defendantAddress: "123 Cherry St, Springfield, IL",
        evidence_provided: "Loan agreement, payment receipts.",
        witness_details: "Anna Liu.",
        case_status: "Registered",
      },
      {
        case_title: "Davis vs. Green",
        case_description: "Tenant eviction case.",
        case_type: CaseType.Real_Estate,
        filing_date: "2024-05-22",
        causeOfAction: "Eviction",
        urgency_level: "High",
        plaintiffName: "Jessica Davis",
        plaintiffContactEmail: "jessica.davis@example.com",
        plaintiffContactPhone: "555-0133",
        plaintiffAddress: "456 Willow St, Springfield, IL",
        defendantName: "Mark Green",
        defendantContactEmail: "mark.green@example.com",
        defendantContactPhone: "555-0134",
        defendantAddress: "789 Maple St, Springfield, IL",
        evidence_provided: "Lease agreement, rent payment history.",
        witness_details: "Tom Clark.",
        case_status: "Filed",
      },
      {
        case_title: "Martinez vs. Lewis",
        case_description: "Copyright infringement case.",
        case_type: CaseType.Intellectual_Property,
        filing_date: "2024-06-15",
        causeOfAction: "Copyright Violation",
        urgency_level: "Medium",
        plaintiffName: "Sofia Martinez",
        plaintiffContactEmail: "sofia.martinez@example.com",
        plaintiffContactPhone: "555-0145",
        plaintiffAddress: "321 Birch St, Springfield, IL",
        defendantName: "Anna Lewis",
        defendantContactEmail: "anna.lewis@example.com",
        defendantContactPhone: "555-0146",
        defendantAddress: "654 Cedar St, Springfield, IL",
        evidence_provided: "Published works, registration certificates.",
        witness_details: "Emily Brown.",
        case_status: "Closed",
      },
      {
        case_title: "Smith vs. Brown",
        case_description: "Divorce and custody battle.",
        case_type: CaseType.Family_Law,
        filing_date: "2024-07-09",
        causeOfAction: "Divorce",
        urgency_level: "High",
        plaintiffName: "Sarah Smith",
        plaintiffContactEmail: "sarah.smith@example.com",
        plaintiffContactPhone: "555-0155",
        plaintiffAddress: "111 Main St, Springfield, IL",
        defendantName: "James Brown",
        defendantContactEmail: "james.brown@example.com",
        defendantContactPhone: "555-0156",
        defendantAddress: "222 Second St, Springfield, IL",
        evidence_provided: "Marriage certificate, custody agreements.",
        witness_details: "John White.",
        case_status: "Requested",
      },
      {
        case_title: "Clark vs. Thompson",
        case_description: "Fraud case regarding investment.",
        case_type: CaseType.Financial,
        filing_date: "2024-08-01",
        causeOfAction: "Fraud",
        urgency_level: "Medium",
        plaintiffName: "Laura Clark",
        plaintiffContactEmail: "laura.clark@example.com",
        plaintiffContactPhone: "555-0167",
        plaintiffAddress: "333 Oak St, Springfield, IL",
        defendantName: "Robert Thompson",
        defendantContactEmail: "robert.thompson@example.com",
        defendantContactPhone: "555-0168",
        defendantAddress: "444 Pine St, Springfield, IL",
        evidence_provided: "Investment contracts, communication records.",
        witness_details: "Jessica Green.",
        case_status: "Registered",
      },
      {
        case_title: "Harris vs. White",
        case_description: "Insurance claim dispute.",
        case_type: CaseType.Insurance,
        filing_date: "2024-09-14",
        causeOfAction: "Insurance Claim",
        urgency_level: "Low",
        plaintiffName: "Daniel Harris",
        plaintiffContactEmail: "daniel.harris@example.com",
        plaintiffContactPhone: "555-0179",
        plaintiffAddress: "555 Elm St, Springfield, IL",
        defendantName: "Cynthia White",
        defendantContactEmail: "cynthia.white@example.com",
        defendantContactPhone: "555-0180",
        defendantAddress: "666 Maple St, Springfield, IL",
        evidence_provided: "Claim documents, policy agreements.",
        witness_details: "Robert King.",
        case_status: "Filed",
      },
      {
        case_title: "Lopez vs. Hall",
        case_description: "Dispute over employee termination.",
        case_type: CaseType.Employment,
        filing_date: "2024-10-11",
        causeOfAction: "Wrongful Termination",
        urgency_level: "High",
        plaintiffName: "Elena Lopez",
        plaintiffContactEmail: "elena.lopez@example.com",
        plaintiffContactPhone: "555-0191",
        plaintiffAddress: "777 Willow St, Springfield, IL",
        defendantName: "Thomas Hall",
        defendantContactEmail: "thomas.hall@example.com",
        defendantContactPhone: "555-0192",
        defendantAddress: "888 Oak St, Springfield, IL",
        evidence_provided: "Employment records, termination letter.",
        witness_details: "Jessica Adams.",
        case_status: "Requested",
      },
      {
        case_title: "Walker vs. Scott",
        case_description: "Claim regarding harassment in the workplace.",
        case_type: CaseType.Employment,
        filing_date: "2024-11-20",
        causeOfAction: "Harassment",
        urgency_level: "Medium",
        plaintiffName: "Kevin Walker",
        plaintiffContactEmail: "kevin.walker@example.com",
        plaintiffContactPhone: "555-0203",
        plaintiffAddress: "999 Pine St, Springfield, IL",
        defendantName: "Barbara Scott",
        defendantContactEmail: "barbara.scott@example.com",
        defendantContactPhone: "555-0204",
        defendantAddress: "111 Cedar St, Springfield, IL",
        evidence_provided: "Witness statements, HR reports.",
        witness_details: "Michael Thomas.",
        case_status: "Filed",
    },
    // Add more cases as needed
];

export default cases;
